
package org.jinouts.webservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2012-11-06T17:16:21.609+08:00
 * Generated source version: 2.6.3
 * 
 */
public final class Login_LoginPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.webservice.jinouts.org/", "LoginService");

    private Login_LoginPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoginService ss = new LoginService(wsdlURL, SERVICE_NAME);
        Login port = ss.getLoginPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_user = "";
        java.lang.String _login_pass = "";
        org.jinouts.webservice.service.LoginServiceResponse _login__return = port.login(_login_user, _login_pass);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
