DROP TABLE ACCOUNT;

CREATE TABLE ACCOUNT (
    ACC_ID INT PRIMARY KEY,
    ACC_FIRST_NAME VARCHAR(255),
    ACC_LAST_NAME VARCHAR(255),
    ACC_EMAIL VARCHAR(255)
);

INSERT INTO ACCOUNT VALUES (
    1, 'a', 'b', 'a@b.com'
);
