package domain;

public class Account {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ACCOUNT.ACC_ID
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ACCOUNT.ACC_FIRST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    private String firstName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ACCOUNT.ACC_LAST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    private String lastName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ACCOUNT.ACC_EMAIL
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    private String emailAddress;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ACCOUNT.ACC_ID
     *
     * @return the value of ACCOUNT.ACC_ID
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ACCOUNT.ACC_ID
     *
     * @param id the value for ACCOUNT.ACC_ID
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ACCOUNT.ACC_FIRST_NAME
     *
     * @return the value of ACCOUNT.ACC_FIRST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ACCOUNT.ACC_FIRST_NAME
     *
     * @param firstName the value for ACCOUNT.ACC_FIRST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ACCOUNT.ACC_LAST_NAME
     *
     * @return the value of ACCOUNT.ACC_LAST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ACCOUNT.ACC_LAST_NAME
     *
     * @param lastName the value for ACCOUNT.ACC_LAST_NAME
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ACCOUNT.ACC_EMAIL
     *
     * @return the value of ACCOUNT.ACC_EMAIL
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ACCOUNT.ACC_EMAIL
     *
     * @param emailAddress the value for ACCOUNT.ACC_EMAIL
     *
     * @ibatorgenerated Wed Jun 30 15:50:27 CST 2010
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
}